### ISSUE TITLE
merged.csv

### ISSUE THREAD

**Issue by dhvalden** [ucinlp/covid19-backend#59]
is there instruction of how to reproduce the merged.csv file? why and what are the use of the random number columns?

**Comment by atleastbeth3** [comment]
`merged.csv` should be a `.csv` consisting of 7 columns in the following order with no headers: Random number 1, Misconception ID , Misconception, Tweet, Random Number 2, Annotated Label, Tweet ID.

Misconception ID, Misconception, Tweet ID, and Annotated Label are from the [COVIDLies dataset](https://github.com/ucinlp/covid19-data).

Tweets need to be retrieved from Twitter using the Tweet IDs provided in the dataset.

The random number columns are an artifact of how the dataset was constructed. They can be populated with any numbers.

**Comment by rloganiv** [comment]
Can I close this issue?

**Comment by dhvalden** [comment]
yeah sure!

**Comment by rloganiv** [comment]
Thanks!
