### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by dhvalden** [ucinlp/covid19-backend#60]
Hello!
I'm trying to repreduce the results of the paper https://openreview.net/pdf?id=FCna-s-ZaIE but I'm struck in the section of training the models using a .jsonl file. Where thoe jsonl files come from? are they need to be generated by the database? Is the training data the one in covid-lies repo?
Thanks a lot!

**Comment by atleastbeth3** [comment]
Hi, 
The training .jsonl files are from [SNLI](https://nlp.stanford.edu/projects/snli/), [MultiNLI](https://cims.nyu.edu/~sbowman/multinli/), and [MedNLI](https://physionet.org/content/mednli/1.0.0/) . The CovidLies dataset is only used for evaluation not training.

**Comment by dhvalden** [comment]
Thanks a lot. I'm gonna keep asking questions is that's alright. I really want to be able to reproduce this study.
